# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-10 05:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='selectChoice',
            field=models.BooleanField(default=False),
        ),
    ]
